- hosts: jellyfin
  become: true
  tasks:
  - name: Update && Upgrade
    shell: apt update && apt upgrade -y
- hosts: nextcloud
  become: true
  tasks:
  - name: Update && Upgrade
    shell: apt update && apt upgrade -y
